"""
Test data generator for creating comprehensive mock medical scenarios.

This module provides utilities for generating synthetic test data that is
HIPAA-compliant and realistic for testing the Prior Authorization System.

⚠️  IMPORTANT: ALL DATA GENERATED BY THIS MODULE IS SYNTHETIC AND FOR TESTING ONLY
⚠️  NO REAL PATIENT INFORMATION SHOULD EVER BE USED IN TESTS
⚠️  ALL GENERATED DATA IS CLEARLY MARKED AS SYNTHETIC/TEST DATA
"""

import random
import re
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Any, Optional, Set
from dataclasses import dataclass
import warnings

from src.models.authorization import AuthorizationRequest, AuthorizationDecision
from src.models.patient import PatientDemographics
from src.models.medical_codes import ICD10Code, CPTCode
from src.models.enums import (
    RequestStatus, DecisionStatus, UrgencyLevel, Gender, ProcedureType
)


@dataclass
class MedicalScenario:
    """Represents a complete medical scenario for testing.
    
    ⚠️  ALL DATA IN THIS SCENARIO IS SYNTHETIC AND FOR TESTING ONLY
    """
    name: str
    patient: PatientDemographics
    diagnosis_codes: List[ICD10Code]
    procedure_codes: List[CPTCode]
    clinical_notes: str
    urgency_level: UrgencyLevel
    procedure_type: ProcedureType
    expected_decision: DecisionStatus
    expected_reasoning: List[str]
    policy_references: List[str]
    is_synthetic: bool = True  # Always True for test data
    synthetic_marker: str = "SYNTHETIC_TEST_DATA"


class PHIValidationError(Exception):
    """Raised when potential real PHI is detected in test data."""
    pass


class DataGenerator:
    """Generates comprehensive test data for various medical scenarios.
    
    ⚠️  IMPORTANT: This class generates SYNTHETIC data only for testing purposes.
    ⚠️  All generated data is clearly marked as synthetic and compliant with HIPAA.
    ⚠️  Real patient information must NEVER be used in test data.
    """
    
    # Patterns that might indicate real PHI (to be avoided)
    POTENTIAL_PHI_PATTERNS = {
        'ssn': re.compile(r'\b\d{3}-\d{2}-\d{4}\b'),
        'phone': re.compile(r'\b\d{3}-\d{3}-\d{4}\b|\b\(\d{3}\)\s*\d{3}-\d{4}\b'),
        'email': re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'),
        'real_names': re.compile(r'\b(John|Jane|Smith|Johnson|Williams|Brown|Davis|Miller|Wilson|Moore|Taylor|Anderson|Thomas|Jackson|White|Harris|Martin|Thompson|Garcia|Martinez|Robinson|Clark|Rodriguez|Lewis|Lee|Walker|Hall|Allen|Young|Hernandez|King|Wright|Lopez|Hill|Scott|Green|Adams|Baker|Gonzalez|Nelson|Carter|Mitchell|Perez|Roberts|Turner|Phillips|Campbell|Parker|Evans|Edwards|Collins|Stewart|Sanchez|Morris|Rogers|Reed|Cook|Morgan|Bell|Murphy|Bailey|Rivera|Cooper|Richardson|Cox|Howard|Ward|Torres|Peterson|Gray|Ramirez|James|Watson|Brooks|Kelly|Sanders|Price|Bennett|Wood|Barnes|Ross|Henderson|Coleman|Jenkins|Perry|Powell|Long|Patterson|Hughes|Flores|Washington|Butler|Simmons|Foster|Gonzales|Bryant|Alexander|Russell|Griffin|Diaz|Hayes)\b', re.IGNORECASE),
        'address': re.compile(r'\b\d{1,5}\s+(Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct|Place|Pl)\b', re.IGNORECASE),
        'zip_code': re.compile(r'\b\d{5}(-\d{4})?\b'),
        'date_of_birth': re.compile(r'\b(0[1-9]|1[0-2])/(0[1-9]|[12]\d|3[01])/\d{4}\b')
    }
    
    # Common ICD-10 codes for imaging
    COMMON_DIAGNOSIS_CODES = {
        "M25.511": "Pain in right shoulder",
        "M25.512": "Pain in left shoulder", 
        "M54.5": "Low back pain",
        "G93.1": "Anoxic brain damage, not elsewhere classified",
        "S72.001A": "Fracture of unspecified part of neck of right femur, initial encounter",
        "M79.3": "Panniculitis, unspecified",
        "R06.02": "Shortness of breath",
        "M25.561": "Pain in right knee",
        "G44.1": "Vascular headache, not elsewhere classified",
        "M47.816": "Spondylosis without myelopathy or radiculopathy, lumbar region"
    }
    
    # Common CPT codes for imaging
    COMMON_PROCEDURE_CODES = {
        "70551": "MRI brain without contrast",
        "70552": "MRI brain with contrast", 
        "72148": "MRI lumbar spine without contrast",
        "72149": "MRI lumbar spine with contrast",
        "73221": "MRI upper extremity without contrast",
        "73222": "MRI upper extremity with contrast",
        "74177": "CT abdomen and pelvis with contrast",
        "71250": "CT chest without contrast",
        "72128": "CT lumbar spine without contrast",
        "76700": "Ultrasound abdomen complete"
    }
    
    def __init__(self):
        """Initialize the test data generator."""
        self.scenario_counter = 0
        self.synthetic_marker = "SYNTHETIC_TEST_DATA"
        self._validate_environment()
    
    def _validate_environment(self):
        """Validate that we're in a test environment."""
        import os
        if os.getenv('PA_ENVIRONMENT') not in ['testing', 'test', 'development', 'dev']:
            warnings.warn(
                "DataGenerator should only be used in test environments. "
                "Ensure PA_ENVIRONMENT is set to 'testing' or 'development'.",
                UserWarning
            )
    
    def _validate_no_phi(self, text: str, field_name: str = "data") -> None:
        """Validate that text doesn't contain potential PHI patterns.
        
        Args:
            text: Text to validate
            field_name: Name of the field being validated (for error messages)
            
        Raises:
            PHIValidationError: If potential PHI is detected
        """
        if not text:
            return
            
        for pattern_name, pattern in self.POTENTIAL_PHI_PATTERNS.items():
            if pattern.search(text):
                raise PHIValidationError(
                    f"Potential {pattern_name} detected in {field_name}: {text[:50]}... "
                    f"All test data must be synthetic. Use clearly synthetic values instead."
                )
    
    def _add_synthetic_markers(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Add synthetic data markers to generated data.
        
        Args:
            data: Data dictionary to mark as synthetic
            
        Returns:
            Data with synthetic markers added
        """
        data['_synthetic_data'] = True
        data['_test_data_marker'] = self.synthetic_marker
        data['_generated_at'] = datetime.now(timezone.utc).isoformat()
        data['_phi_compliant'] = True
        return data
    
    def generate_patient_demographics(self, age_range: tuple = (18, 80)) -> PatientDemographics:
        """Generate realistic but clearly synthetic patient demographics.
        
        ⚠️  ALL GENERATED DATA IS SYNTHETIC AND FOR TESTING ONLY
        
        Args:
            age_range: Tuple of (min_age, max_age) for patient age
            
        Returns:
            PatientDemographics with synthetic data clearly marked
        """
        age = random.randint(*age_range)
        gender = random.choice([Gender.MALE, Gender.FEMALE])
        
        # Generate clearly synthetic IDs with test markers
        patient_id = f"SYNTH_PAT_{random.randint(1000000, 9999999):07d}_TEST"
        insurance_id = f"SYNTH_INS_{random.randint(1000000, 9999999):07d}_TEST"
        member_id = f"SYNTH_MEM_{random.randint(1000000, 9999999):07d}_TEST"
        
        # Validate no PHI patterns
        self._validate_no_phi(patient_id, "patient_id")
        self._validate_no_phi(insurance_id, "insurance_id")
        self._validate_no_phi(member_id, "member_id")
        
        return PatientDemographics(
            patient_id=patient_id,
            age=age,
            gender=gender,
            insurance_id=insurance_id,
            member_id=member_id
        )
    
    def generate_diagnosis_codes(self, count: int = 1) -> List[ICD10Code]:
        """Generate realistic diagnosis codes."""
        codes = random.sample(list(self.COMMON_DIAGNOSIS_CODES.keys()), min(count, len(self.COMMON_DIAGNOSIS_CODES)))
        return [
            ICD10Code(code=code, description=self.COMMON_DIAGNOSIS_CODES[code])
            for code in codes
        ]
    
    def generate_procedure_codes(self, count: int = 1) -> List[CPTCode]:
        """Generate realistic procedure codes."""
        codes = random.sample(list(self.COMMON_PROCEDURE_CODES.keys()), min(count, len(self.COMMON_PROCEDURE_CODES)))
        return [
            CPTCode(code=code, description=self.COMMON_PROCEDURE_CODES[code])
            for code in codes
        ]
    
    def generate_clinical_notes(self, diagnosis_code: str, procedure_code: str) -> str:
        """Generate realistic but clearly synthetic clinical notes.
        
        ⚠️  ALL GENERATED CLINICAL NOTES ARE SYNTHETIC AND FOR TESTING ONLY
        
        Args:
            diagnosis_code: ICD-10 diagnosis code
            procedure_code: CPT procedure code
            
        Returns:
            Synthetic clinical notes with clear test data markers
        """
        templates = {
            "M25.511": "[SYNTHETIC TEST DATA] Patient reports persistent right shoulder pain for {duration} weeks following {cause}. Conservative treatment with {treatment} has provided limited relief. Physical examination reveals {findings}. [This is synthetic test data for system testing only]",
            "M54.5": "[SYNTHETIC TEST DATA] Patient presents with chronic low back pain lasting {duration} months. Pain is described as {quality} and radiates to {location}. Previous treatments include {treatment}. [This is synthetic test data for system testing only]",
            "G93.1": "[SYNTHETIC TEST DATA] Patient with history of {cause} presenting with neurological symptoms including {symptoms}. Urgent imaging required to assess extent of brain injury. [This is synthetic test data for system testing only]",
            "S72.001A": "[SYNTHETIC TEST DATA] Patient sustained right femoral neck fracture following {mechanism}. Requires immediate imaging to assess fracture pattern and plan surgical intervention. [This is synthetic test data for system testing only]",
            "G44.1": "[SYNTHETIC TEST DATA] Patient reports severe headaches with {characteristics} lasting {duration}. Associated symptoms include {symptoms}. Neuroimaging indicated to rule out secondary causes. [This is synthetic test data for system testing only]"
        }
        
        # Generate random values for template placeholders
        duration = random.randint(2, 12)
        causes = ["sports injury", "fall", "motor vehicle accident", "work-related injury"]
        treatments = ["physical therapy", "NSAIDs", "rest", "ice therapy"]
        findings = ["limited range of motion", "tenderness", "swelling", "muscle spasm"]
        qualities = ["sharp", "dull", "burning", "aching"]
        locations = ["bilateral legs", "right leg", "left leg", "buttocks"]
        symptoms = ["confusion", "memory loss", "weakness", "dizziness"]
        mechanisms = ["fall from height", "motor vehicle accident", "sports injury"]
        characteristics = ["throbbing quality", "photophobia", "nausea", "visual disturbances"]
        
        template = templates.get(diagnosis_code, "[SYNTHETIC TEST DATA] Patient presents with {condition} requiring imaging evaluation. [This is synthetic test data for system testing only]")
        
        clinical_notes = template.format(
            duration=duration,
            cause=random.choice(causes),
            treatment=random.choice(treatments),
            findings=random.choice(findings),
            quality=random.choice(qualities),
            location=random.choice(locations),
            symptoms=random.choice(symptoms),
            mechanism=random.choice(mechanisms),
            characteristics=random.choice(characteristics),
            condition="medical condition"
        )
        
        # Validate no PHI patterns in generated notes
        self._validate_no_phi(clinical_notes, "clinical_notes")
        
        return clinical_notes
    
    def generate_authorization_request(self, scenario_type: str = "routine") -> AuthorizationRequest:
        """Generate a complete synthetic authorization request.
        
        ⚠️  ALL GENERATED DATA IS SYNTHETIC AND FOR TESTING ONLY
        
        Args:
            scenario_type: Type of scenario ("routine", "urgent", "emergent")
            
        Returns:
            AuthorizationRequest with synthetic data clearly marked
        """
        self.scenario_counter += 1
        
        patient = self.generate_patient_demographics()
        diagnosis_codes = self.generate_diagnosis_codes(random.randint(1, 2))
        procedure_codes = self.generate_procedure_codes(1)
        
        # Determine procedure type from CPT code
        procedure_type = self._determine_procedure_type(procedure_codes[0].code)
        
        # Determine urgency based on scenario type
        urgency_mapping = {
            "routine": UrgencyLevel.ROUTINE,
            "urgent": UrgencyLevel.URGENT,
            "emergent": UrgencyLevel.EMERGENT
        }
        urgency = urgency_mapping.get(scenario_type, UrgencyLevel.ROUTINE)
        
        clinical_notes = self.generate_clinical_notes(
            diagnosis_codes[0].code,
            procedure_codes[0].code
        )
        
        # Generate synthetic request ID with clear test marker
        request_id = f"req_SYNTH_TEST_{self.scenario_counter:06d}"
        provider_id = f"SYNTH_PROV_{random.randint(1000, 9999)}_TEST"
        
        # Validate no PHI in generated IDs
        self._validate_no_phi(request_id, "request_id")
        self._validate_no_phi(provider_id, "provider_id")
        
        return AuthorizationRequest(
            request_id=request_id,
            provider_id=provider_id,
            patient_demographics=patient,
            diagnosis_codes=diagnosis_codes,
            procedure_codes=procedure_codes,
            clinical_notes=clinical_notes,
            procedure_type=procedure_type,
            urgency_level=urgency,
            status=RequestStatus.SUBMITTED
        )
    
    def generate_authorization_decision(self, request: AuthorizationRequest, 
                                     decision_type: str = "approved") -> AuthorizationDecision:
        """Generate a synthetic authorization decision for a request.
        
        ⚠️  ALL GENERATED DATA IS SYNTHETIC AND FOR TESTING ONLY
        
        Args:
            request: Authorization request to generate decision for
            decision_type: Type of decision ("approved", "denied", "more_info")
            
        Returns:
            AuthorizationDecision with synthetic data clearly marked
        """
        decision_mapping = {
            "approved": DecisionStatus.APPROVED,
            "denied": DecisionStatus.DENIED,
            "more_info": DecisionStatus.MORE_INFO_NEEDED
        }
        
        status = decision_mapping.get(decision_type, DecisionStatus.APPROVED)
        
        # Generate reasoning based on decision type
        reasoning = self._generate_decision_reasoning(status, request)
        
        # Generate policy references
        policy_references = self._generate_policy_references(request)
        
        # Generate synthetic decision ID with clear test marker
        decision_id = f"dec_SYNTH_TEST_{request.request_id.replace('req_SYNTH_TEST_', '')}"
        
        # Validate no PHI in generated ID
        self._validate_no_phi(decision_id, "decision_id")
        
        decision_data = {
            "decision_id": decision_id,
            "request_id": request.request_id,
            "status": status,
            "reasoning": reasoning,
            "policy_references": policy_references,
            "confidence_score": random.uniform(0.7, 0.99)
        }
        
        if status == DecisionStatus.APPROVED:
            auth_number = f"auth_SYNTH_TEST_{datetime.now(timezone.utc).strftime('%Y%m%d')}_{random.randint(100000, 999999)}"
            self._validate_no_phi(auth_number, "authorization_number")
            decision_data.update({
                "authorization_number": auth_number,
                "valid_until": datetime.now(timezone.utc) + timedelta(days=30)
            })
        elif status == DecisionStatus.MORE_INFO_NEEDED:
            decision_data["additional_info_needed"] = [
                "[SYNTHETIC TEST DATA] Physical therapy notes from past 6 weeks",
                "[SYNTHETIC TEST DATA] Specialist consultation report"
            ]
        elif status == DecisionStatus.DENIED:
            decision_data["alternative_procedures"] = [
                "[SYNTHETIC TEST DATA] Consider conservative treatment for additional 4 weeks",
                "[SYNTHETIC TEST DATA] Physical therapy evaluation recommended"
            ]
        
        return AuthorizationDecision(**decision_data)
    
    def generate_medical_scenarios(self, count: int = 10) -> List[MedicalScenario]:
        """Generate a variety of medical scenarios for comprehensive testing."""
        scenarios = []
        scenario_types = ["routine", "urgent", "emergent"]
        decision_types = ["approved", "denied", "more_info"]
        
        for i in range(count):
            scenario_type = random.choice(scenario_types)
            decision_type = random.choice(decision_types)
            
            request = self.generate_authorization_request(scenario_type)
            decision = self.generate_authorization_decision(request, decision_type)
            
            scenario = MedicalScenario(
                name=f"scenario_{i+1}_{scenario_type}_{decision_type}",
                patient=request.patient_demographics,
                diagnosis_codes=request.diagnosis_codes,
                procedure_codes=request.procedure_codes,
                clinical_notes=request.clinical_notes,
                urgency_level=request.urgency_level,
                procedure_type=request.procedure_type,
                expected_decision=decision.status,
                expected_reasoning=decision.reasoning,
                policy_references=decision.policy_references
            )
            
            scenarios.append(scenario)
        
        return scenarios
    
    def generate_edge_case_scenarios(self) -> List[Dict[str, Any]]:
        """Generate edge case scenarios for testing."""
        return [
            {
                "name": "invalid_diagnosis_code",
                "diagnosis_codes": ["INVALID123"],
                "expected_outcome": "validation_error"
            },
            {
                "name": "invalid_procedure_code", 
                "procedure_codes": ["99999"],
                "expected_outcome": "validation_error"
            },
            {
                "name": "missing_clinical_notes",
                "clinical_notes": "",
                "expected_outcome": "more_info_needed"
            },
            {
                "name": "elderly_patient_high_risk",
                "patient_age": 85,
                "urgency": UrgencyLevel.EMERGENT,
                "expected_outcome": "approved_with_warnings"
            },
            {
                "name": "pediatric_patient",
                "patient_age": 12,
                "expected_outcome": "special_handling"
            }
        ]
    
    def generate_performance_test_data(self, request_count: int = 1000) -> List[AuthorizationRequest]:
        """Generate data for performance testing."""
        requests = []
        scenario_types = ["routine", "urgent", "emergent"]
        
        for i in range(request_count):
            scenario_type = random.choice(scenario_types)
            request = self.generate_authorization_request(scenario_type)
            requests.append(request)
        
        return requests
    
    def _determine_procedure_type(self, cpt_code: str) -> ProcedureType:
        """Determine procedure type from CPT code."""
        if cpt_code.startswith("705"):  # MRI brain codes
            return ProcedureType.MRI
        elif cpt_code.startswith("721"):  # MRI spine codes
            return ProcedureType.MRI
        elif cpt_code.startswith("732"):  # MRI extremity codes
            return ProcedureType.MRI
        elif cpt_code.startswith("712") or cpt_code.startswith("741"):  # CT codes
            return ProcedureType.CT_SCAN
        elif cpt_code.startswith("767"):  # Ultrasound codes
            return ProcedureType.ULTRASOUND
        else:
            return ProcedureType.X_RAY
    
    def _generate_decision_reasoning(self, status: DecisionStatus, 
                                   request: AuthorizationRequest) -> List[str]:
        """Generate realistic decision reasoning."""
        if status == DecisionStatus.APPROVED:
            return [
                f"Patient meets medical necessity criteria for {request.procedure_codes[0].description}",
                f"Diagnosis {request.diagnosis_codes[0].code} is covered under current policy",
                "Conservative treatment duration is adequate",
                "Clinical documentation supports imaging request"
            ]
        elif status == DecisionStatus.DENIED:
            return [
                "Insufficient conservative treatment trial",
                "Clinical documentation does not support medical necessity",
                "Alternative diagnostic methods should be considered first"
            ]
        else:  # MORE_INFO_NEEDED
            return [
                "Additional clinical documentation required",
                "Physical therapy records needed to assess treatment response",
                "Specialist consultation recommended before imaging approval"
            ]
    
    def _generate_policy_references(self, request: AuthorizationRequest) -> List[str]:
        """Generate realistic policy references."""
        references = ["CMS NCD 220.2 - Magnetic Resonance Imaging"]
        
        if request.procedure_type == ProcedureType.MRI:
            references.append("LCD L33721 - MRI Upper Extremity")
        elif request.procedure_type == ProcedureType.CT_SCAN:
            references.append("LCD L33822 - Computed Tomography")
        
        references.append("Payer Policy IMG-001 - Imaging Services")
        
        return references
    
    def validate_test_data_compliance(self, data: Any, data_name: str = "test_data") -> Dict[str, Any]:
        """Validate that test data is PHI-compliant.
        
        Args:
            data: Test data to validate (can be dict, string, or object)
            data_name: Name of the data being validated
            
        Returns:
            Dict with validation results
        """
        validation_result = {
            'is_compliant': True,
            'violations': [],
            'warnings': [],
            'data_name': data_name,
            'validated_at': datetime.now(timezone.utc).isoformat()
        }
        
        # Convert data to string for pattern matching
        if hasattr(data, '__dict__'):
            data_str = str(data.__dict__)
        elif isinstance(data, dict):
            data_str = str(data)
        else:
            data_str = str(data)
        
        # Check for PHI patterns
        for pattern_name, pattern in self.POTENTIAL_PHI_PATTERNS.items():
            matches = pattern.findall(data_str)
            if matches:
                validation_result['is_compliant'] = False
                validation_result['violations'].append({
                    'type': pattern_name,
                    'matches': matches[:5],  # Limit to first 5 matches
                    'description': f"Potential {pattern_name} detected in {data_name}"
                })
        
        # Check for synthetic markers
        if isinstance(data, dict):
            if not data.get('_synthetic_data') and not any('SYNTH' in str(v) or 'TEST' in str(v) for v in data.values()):
                validation_result['warnings'].append(
                    "Data lacks clear synthetic markers. Consider adding synthetic identifiers."
                )
        elif isinstance(data_str, str):
            if 'SYNTHETIC' not in data_str and 'TEST' not in data_str and 'SYNTH' not in data_str:
                validation_result['warnings'].append(
                    "Data lacks clear synthetic markers. Consider adding synthetic identifiers."
                )
        
        return validation_result
    
    def create_phi_compliance_report(self, test_data_samples: List[Any]) -> Dict[str, Any]:
        """Create a comprehensive PHI compliance report for test data.
        
        Args:
            test_data_samples: List of test data samples to validate
            
        Returns:
            Comprehensive compliance report
        """
        report = {
            'report_generated_at': datetime.now(timezone.utc).isoformat(),
            'total_samples_checked': len(test_data_samples),
            'compliant_samples': 0,
            'non_compliant_samples': 0,
            'samples_with_warnings': 0,
            'violation_summary': {},
            'recommendations': [],
            'overall_compliance': True
        }
        
        for i, sample in enumerate(test_data_samples):
            validation = self.validate_test_data_compliance(sample, f"sample_{i}")
            
            if validation['is_compliant']:
                report['compliant_samples'] += 1
            else:
                report['non_compliant_samples'] += 1
                report['overall_compliance'] = False
                
                # Track violation types
                for violation in validation['violations']:
                    violation_type = violation['type']
                    if violation_type not in report['violation_summary']:
                        report['violation_summary'][violation_type] = 0
                    report['violation_summary'][violation_type] += 1
            
            if validation['warnings']:
                report['samples_with_warnings'] += 1
        
        # Generate recommendations
        if report['non_compliant_samples'] > 0:
            report['recommendations'].append(
                "Remove or replace any real PHI with synthetic alternatives"
            )
        
        if report['samples_with_warnings'] > 0:
            report['recommendations'].append(
                "Add clear synthetic data markers to all test data"
            )
        
        if report['overall_compliance']:
            report['recommendations'].append(
                "Test data appears PHI-compliant. Continue monitoring for compliance."
            )
        
        return report


# Utility functions for test data
def create_test_request_batch(count: int = 100) -> List[AuthorizationRequest]:
    """Create a batch of test requests for load testing."""
    generator = DataGenerator()
    return [generator.generate_authorization_request() for _ in range(count)]


def create_validation_test_cases() -> List[Dict[str, Any]]:
    """Create test cases for validation testing."""
    return [
        {
            "name": "valid_request",
            "data": DataGenerator().generate_authorization_request(),
            "expected_valid": True
        },
        {
            "name": "invalid_diagnosis_code",
            "modifications": {"diagnosis_codes": [{"code": "INVALID", "description": "Invalid"}]},
            "expected_valid": False
        },
        {
            "name": "missing_procedure_code",
            "modifications": {"procedure_codes": []},
            "expected_valid": False
        }
    ]


def create_policy_test_scenarios() -> List[Dict[str, Any]]:
    """Create scenarios for policy validation testing."""
    return [
        {
            "name": "covered_procedure",
            "procedure_code": "73221",
            "diagnosis_code": "M25.511",
            "expected_covered": True
        },
        {
            "name": "experimental_procedure",
            "procedure_code": "99999",
            "diagnosis_code": "M25.511", 
            "expected_covered": False
        },
        {
            "name": "off_label_use",
            "procedure_code": "73221",
            "diagnosis_code": "Z00.00",
            "expected_covered": False
        }
    ]